### ISSUE TITLE
Dot imports

### ISSUE THREAD

**Issue by dustinmatlock** [feyeleanor/GoNotebook#1]
Is there a specific reason the book uses dot imports when this is generally thought of as bad practice?

**Comment by feyeleanor** [comment]
Generally I use dot imports where it makes code easier to read, both in the book and in my conference talks. In these contexts I'll generally be explaining in detail what's happening in the code so there doesn't tend to be any ambiguity.

My style in general has always been divergent from the Go mainstream, even back in 2009/10 when there were only a few dozen of us gophers. I don't think that's a bad thing.
